nameOverride: meal-planner-backend

livenessProbe:
  initialDelaySeconds: 40
  failureThreshold: 4
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  tcpSocket:
    port: http
readinessProbe:
  initialDelaySeconds: 40
  failureThreshold: 4
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  tcpSocket:
    port: http

ports:
  - name: http
    containerPort: 9090
    protocol: TCP

resources:
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: http

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

volumeMounts:
  - name: tmp
    mountPath: /tmp

volumes:
  - name: tmp
    emptyDir: {}

ingress:
  enabled: true
  tlsEnabled: true
  servicePort: 9090
  tlsSecretName: meal-planner-backend-tls
  ingressClassName: nginx